package convoy.pdf;

import convoy.gui.VehicleGrid;
import convoy.objects.Radio;
import java.io.*;
import java.net.URL;
import java.net.URLDecoder;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * @author Mike Moye <mtm5313@psu.edu>
 * @version 1.0
 * @since 2014-02-27
 *
 * <p>
 * This class is used to create the pdf. I creates the pdf using the pdf library
 * by grabbing the generated html and opening the pdf in the user's default pdf
 * application.
 * </p>
 */
public class GenerateHtml {

    /**
     * Default constructor
     */
    public GenerateHtml() {
    }

    /**
     * <p>
     * This method is used to generate the HTML and CSS. It grabs all the
     * attribute from the convoy and adds them to the HTML file. The CSS is
     * embedded in the HTML file.
     * </p>
     *
     * @param watermark
     * @param classification
     * @param missionNumber
     * @param leftFrom
     * @param leftTo
     * @param leftAdditionalText
     * @param cc
     * @param acc
     * @param stagingArea
     * @param fromLU
     * @param toLU
     * @param fromSP
     * @param toSP
     * @param freqs
     * @param rightAdditionalText
     * @param additionalText
     * @param vehicleGrid
     */
    public void generateHtml(String watermark,
            String classification,
            String missionNumber,
            String leftFrom,
            String leftTo,
            String leftAdditionalText,
            String cc,
            String acc,
            String stagingArea,
            //String rightFrom,
            //String rightTo,
            String fromLU,
            String toLU,
            String fromSP,
            String toSP,
            ArrayList<Radio> freqs,
            String rightAdditionalText,
            String additionalText,
            VehicleGrid vehicleGrid) {

        String radio = "";

        if (!freqs.get(0).getName().equalsIgnoreCase("")) {
            radio = "                           <tr>"
                    + "                             <td colspan=\"6\">"
                    + "                                <table id=\"freqTable\">\n"
                    + "                                    <!-- frequency table //-->\n"
                    + "                                    <tr>\n"
                    + "                                        <td class=\"label\" colspan=\"6\">Frequencys -</td>\n"
                    + "                                    </tr>\n"
                    + "                                    <tr>\n"
                    + "                                        <td class=\"label\">CH1:</td>\n"
                    + "                                        <td class=\"data\" id=\"ch1Name\">" + freqs.get(0).getName() + "</td>\n"
                    + "                                        <td class=\"data\" id=\"ch1Freq\">" + freqs.get(0).getFreq() + "</td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                                <!-- end frequency table //-->\n"
                    + "                             </td>"
                    + "                         </tr>";
        }
        if (!freqs.get(1).getName().equalsIgnoreCase("")) {
            radio = "                           <tr>\n"
                    + "                            <!-- frequency row //-->\n"
                    + "                            <td colspan=\"6\">\n"
                    + "                                 <table id=\"freqTable\">\n"
                    + "                                    <!-- frequency table //-->\n"
                    + "                                    <tr>\n"
                    + "                                        <td class=\"label\" colspan=\"6\">Frequencys -</td>\n"
                    + "                                    </tr>\n"
                    + "                                    <tr>\n"
                    + "                                        <td class=\"label\">CH1:</td>\n"
                    + "                                        <td class=\"data\" id=\"ch1Name\">" + freqs.get(0).getName() + "</td>\n"
                    + "                                        <td class=\"data\" id=\"ch1Freq\">" + freqs.get(0).getFreq() + "</td>\n"
                    + "                                        <td class=\"label\">CH2:</td>\n"
                    + "                                        <td class=\"data\" id=\"ch2Name\">" + freqs.get(1).getName() + "</td>\n"
                    + "                                        <td class=\"data\" id=\"ch2Freq\">" + freqs.get(1).getFreq() + "</td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                                <!-- end frequency table //-->\n"
                    + "                            </td>\n"
                    + "                        </tr>\n";
        }

        if (!freqs.get(2).getName().equalsIgnoreCase("")) {
            radio = "                        <tr>\n"
                    + "                            <!-- frequency row //-->\n"
                    + "                            <td colspan=\"6\">\n" + "                    <table id=\"freqTable\">\n"
                    + "                                    <!-- frequency table //-->\n"
                    + "                                    <tr>\n"
                    + "                                        <td class=\"label\" colspan=\"6\">Frequencys -</td>\n"
                    + "                                    </tr>\n"
                    + "                                    <tr>\n"
                    + "                                        <td class=\"label\">CH1:</td>\n"
                    + "                                        <td class=\"data\" id=\"ch1Name\">" + freqs.get(0).getName() + "</td>\n"
                    + "                                        <td class=\"data\" id=\"ch1Freq\">" + freqs.get(0).getFreq() + "</td>\n"
                    + "                                        <td class=\"label\">CH2:</td>\n"
                    + "                                        <td class=\"data\" id=\"ch2Name\">" + freqs.get(1).getName() + "</td>\n"
                    + "                                        <td class=\"data\" id=\"ch2Freq\">" + freqs.get(1).getFreq() + "</td>\n"
                    + "                                    </tr>\n"
                    + "                                     <tr>\n"
                    + "                                        <td class=\"label\">CH3:</td>\n"
                    + "                                        <td class=\"data\" id=\"ch3Name\">" + freqs.get(2).getName() + "</td>\n"
                    + "                                        <td class=\"data\" id=\"ch3Freq\">" + freqs.get(2).getFreq() + "</td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                                <!-- end frequency table //-->\n" + "                            </td>\n"
                    + "                        </tr>\n";
        }

        if (!freqs.get(3).getName().equalsIgnoreCase("")) {
            radio
                    = "                        <tr>\n"
                    + "                            <!-- frequency row //-->\n"
                    + "                            <td colspan=\"6\">\n" + "                    <table id=\"freqTable\">\n"
                    + "                    <table id=\"freqTable\">\n"
                    + "                                    <!-- frequency table //-->\n"
                    + "                                    <tr>\n"
                    + "                                        <td class=\"label\" colspan=\"6\">Frequencys -</td>\n"
                    + "                                    </tr>\n"
                    + "                                    <tr>\n"
                    + "                                        <td class=\"label\">CH1:</td>\n"
                    + "                                        <td class=\"data\" id=\"ch1Name\">" + freqs.get(0).getName() + "</td>\n"
                    + "                                        <td class=\"data\" id=\"ch1Freq\">" + freqs.get(0).getFreq() + "</td>\n"
                    + "                                        <td class=\"label\">CH2:</td>\n"
                    + "                                        <td class=\"data\" id=\"ch2Name\">" + freqs.get(1).getName() + "</td>\n"
                    + "                                        <td class=\"data\" id=\"ch2Freq\">" + freqs.get(1).getFreq() + "</td>\n"
                    + "                                    </tr>\n"
                    + "                                     <tr>\n"
                    + "                                        <td class=\"label\">CH3:</td>\n"
                    + "                                        <td class=\"data\" id=\"ch3Name\">" + freqs.get(2).getName() + "</td>\n"
                    + "                                        <td class=\"data\" id=\"ch3Freq\">" + freqs.get(2).getFreq() + "</td>\n"
                    + "                                        <td class=\"label\">CH4:</td>\n"
                    + "                                        <td class=\"data\" id=\"ch4Name\">" + freqs.get(3).getName() + "</td>\n"
                    + "                                        <td class=\"data\" id=\"ch4Freq\">" + freqs.get(3).getFreq() + "</td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                                <!-- end frequency table //-->\n" + "                            </td>\n"
                    + "                        </tr>\n";
        }

        if (rightAdditionalText.equalsIgnoreCase("") || rightAdditionalText.equalsIgnoreCase("Additional Information Goes Here")) {
            rightAdditionalText = "";
        } else {
            rightAdditionalText = "             <tr>\n"
                    + "                            <td class=\"additionalText\" colspan=\"6\">\n"
                    + "                                <pre>\n"
                    + rightAdditionalText
                    + "                                 </pre>\n"
                    + "                            </td>\n"
                    + "                        </tr>\n";
        }

        if (leftAdditionalText.equalsIgnoreCase("") || leftAdditionalText.equalsIgnoreCase("Additional Information Goes Here")) {
            leftAdditionalText = "";
        } else {
            leftAdditionalText = "                        <tr>\n"
                    + "                                     <td class=\"additionalText\" colspan=\"3\" id=\"leftAdditionaInfo\">\n"
                    + "                                         <pre>\n"
                    + "" + leftAdditionalText + "\n"
                    + "                                         </pre>\n"
                    + "                                     </td>\n"
                    + "                                 </tr>\n";
        }

        if (additionalText.equalsIgnoreCase("Additional Information Goes Here") || additionalText.equalsIgnoreCase("Additional Information Goes Here")) {
            additionalText = "";
        } else {
            additionalText = "            <tr class=\"rows\">\n"
                    + "                <!-- second row //-->\n"
                    + "                <td class=\"additionalText\" colspan=\"3\">" + additionalText + "</td>\n"
                    + "            </tr>\n";
        }

        String classificationColor;

        if (classification.equalsIgnoreCase("SECRET") || classification.equalsIgnoreCase("TOP SECRET") || classification.equalsIgnoreCase("CONFEDIENTAL")) {
            classificationColor = "red";
        } else {
            classificationColor = "black";
        }

        try {
            File f = null;
            try{
                 f = new File(getProgramPath() + "\\conx\\html\\convoy.html");
                 
                 System.out.print(f);
                 
            }catch(Exception ex){
                
            }finally{
            
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(f))) {
                bw.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n"
                        + "\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n"
                        + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                        + "\n"
                        + "<head>\n"
                        + "    <title></title>\n"
                        + "    <style type=\"text/css\">\n"
                        + "        body {\n"
                        + "            //background-color: rgb(194, 178, 128);\n"
                        + "        }\n"
                        + "        div,\n"
                        + "        table {\n"
                        + "            width: 100%;\n"
                        + "            //border: 1px solid #000;\n"
                        + "            height: 100%;\n"
                        + "            font-size: 14pt;\n"
                        + "        }\n"
                        + "        td {\n"
                        + "            border: 1px solid #000;\n"
                        + "            background-color: white;\n"
                        + "        }\n"
                        + "        .label {\n"
                        + "            font-weight: bold;\n"
                        + "            font-family: capture;\n"
                        + "        }\n"
                        + "        .leftLabel {\n"
                        + "            font-weight: bold;\n"
                        + "            font-family: capture;\n"
                        + "            text-align: center;\n"
                        + "        }\n"
                        + "        .data {\n"
                        + "             font-weight: normal;\n"
                        + "             text-align: left;\n"
                        + "        }\n"
                        + "        .leftData {\n"
                        + "             font-weight: normal;\n"
                        + "             text-align: center;\n"
                        + "        }\n"
                        + "        #freqTable {\n"
                        + "            border: 0;\n"
                        + "        }\n"
                        + "        .rows {\n"
                        + "            border: red solid 1px;\n"
                        + "            height: 33%;\n"
                        + "        }\n"
                        + "        .vehicle td{\n"
                        + "            //height: 250px;\n"
                        + "            text-align: center;\n"
                        + "            border: 0;\n"
                        + "            vertical-align: bottom;\n"
                        + "        }\n"
                        + "        #leftMissionInfo {\n"
                        + "            font-size: 18pt;\n"
                        + "            //border-right: 5px solid red;\n"
                        + "            width: 40%;\n"
                        + "            table-layout: fixed;\n"
                        + "        }\n"
                        + "        .additionalText {\n"
                        + "            height: 100px;\n"
                        + "        }\n"
                        + "        #unitPatch img {\n"
                        + "            width: 202px;\n"
                        + "            height: 172px;\n"
                        + "        }\n"
                        + "        .redBorder {\n"
                        + "            border-top: red solid 5px;\n"
                        + "            border-bottom: red solid 5px;\n"
                        + "            padding-top: 10px;\n"
                        + "            padding-bottom: 10px;\n"
                        + "        }\n"
                        + "        #classification{"
                        + "              text-align: center;"
                        + "              font-weight: bold;"
                        + "              font-size: 24pt;"
                        + "              color: " + classificationColor + ";"
                        + "         }\n"
                        + "        .driver{"
                        + "             color: LimeGreen;"
                        + "         }\n"
                        + "        .midBorder {\n"
                        + "            border-top: red solid 5px;\n"
                        + "        }\n"
                        + "        .picCell{"
                        + "             max-width:52px;"
                        + "             width:52px;"
                        + "         }"
                        + "        .3rdOfPicHeight{"
                        + "             height: 56px"
                        + "         }"
                        + "    </style>\n"
                        + "</head>\n"
                        + "\n"
                        + "<body>\n"
                        + "    <div>\n"
                        + "        <table>\n"
                        + "            <!-- main table //-->\n"
                        + "            <tr class=\"rows\">\n"
                        + "                <!-- first row //-->\n"
                        + "                <td style=\"width: 40%;\" valign=\"top\" id=\"leftMissionInfo\">\n"
                        + "                    <table id=\"leftMissionInfoTable\">\n"
                        + "                        <!-- left mission info table //-->\n"
                        + "                        <tr>\n"
                        + "                            <td colspan=\"3\" id=\"classification\">" + classification + "</td>\n"
                        + "                        </tr>\n"
                        + "                        <tr>\n"
                        + "                            <td class=\"picCell\" colspan=\"1\" rowspan=\"4\" id=\"unitPatch\"><img src=\"" + "file:\\" + watermark + "\" alt=\"unitPatch\"/></td>\n"
                        + "                        </tr>\n"
                        + "                        <tr>\n"
                        + "                            <td class=\"leftLabel\">Mission #</td>\n"
                        + "                            <td class=\"leftData\" id=\"misisonNumber\">" + missionNumber + "</td>\n"
                        + "                        </tr>\n"
                        + "                        <tr>\n"
                        + "                            <td class=\"leftLabel\">Start Point:</td>\n"
                        + "                            <td class=\"leftData\" id=\"leftFrom\">" + leftFrom + "</td>\n"
                        + "                        </tr>\n"
                        + "                        <tr>\n"
                        + "                            <td class=\"leftLabel\">Rally Point:</td>\n"
                        + "                            <td class=\"leftData\" id=\"leftTo\">" + leftTo + "</td>\n"
                        + "                        </tr>\n"
                        + leftAdditionalText
                        + "                    </table>\n"
                        + "                    <!-- end left mission info table //-->\n"
                        + "                </td>\n"
                        + "                <td style=\"width: 60%;\" valign=\"top\">\n"
                        + "                    <table>\n"
                        + "                        <!-- right mission info table //-->\n"
                        + "                        <tr>\n"
                        + "                            <!-- cc and acc row //-->\n"
                        + "                            <td class=\"label\">CC:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=\"data\">" + cc + "</span></td>\n"
                        + "                            <td class=\"label\">ACC:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=\"data\">" + acc + "</span></td>\n"
                        + "                        </tr>\n"
                        + "                        <tr>\n"
                        + "                            <!-- staging area row //-->\n"
                        + "                            <td class=\"label\" colspan=\"2\">Staging Area:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=\"data\">" + stagingArea + "</span></td>\n"
                        + "                        </tr>\n"
                        + "                        <tr>\n"
                        + "                            <!-- from l/u sp //-->\n"
                        + "                            <td class=\"label\">Start Point Linkup Time:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=\"data\">" + fromLU + "</span></td>\n"
                        + "                            <td class=\"label\">Start Point SP Time:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=\"data\">" + fromSP + "</span></td>\n"
                        + "                        </tr>\n"
                        + "                        <tr>\n"
                        + "                            <!-- to l/u sp//-->\n"
                        + "                            <td class=\"label\">Rally Point Linkup Time:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=\"data\">" + toLU + "</span></td>\n"
                        + "                            <td class=\"label\">Rally Point SP Time:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=\"data\">" + toSP + "</span></td>\n"
                        + "                        </tr>\n"
                        + radio
                        + rightAdditionalText
                        + "                    </table>\n"
                        + "                    <!-- end right mission info table //-->\n"
                        + "                </td>\n"
                        + "            </tr>\n"
                        + "            <tr class=\"rows\">\n"
                        + "                <!-- third row //-->\n"
                        + "                <td colspan=\"2\">\n"
                        + "                    <table class=\"redBorder\">\n"
                        + "                        <tr>\n"
                        + "                            <td class=\"vehicle\">"
                        + "                                     <table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(0).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(0).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(0).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(0).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(0).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(0).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(0).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "                            </td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "                                     <table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(1).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(1).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(1).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(1).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(1).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(1).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(1).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "                                     <table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(2).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(2).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(2).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(2).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(2).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(2).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(2).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "                                     <table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(3).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(3).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(3).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(3).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(3).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(3).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(3).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "                                     <table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(4).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(4).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(4).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(4).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(4).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(4).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(4).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "                                     <table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(5).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(5).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(5).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(5).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(5).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(5).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(5).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "                                     <table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(6).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(6).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(6).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(6).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(6).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(6).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(6).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "                                     <table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(7).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(7).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(7).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(7).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(7).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(7).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(7).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                        </tr>\n"
                        + "                        <tr>\n"
                        + "                             <td class=\"midBorder\" colspan=\"8\"></td>\n"
                        + "                         </tr>\n"
                        + "                        <tr>\n"
                        + "                            <td class=\"vehicle\">"
                        + "                                     <table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(8).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(8).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(8).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(8).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(8).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(8).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(8).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "                            </td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "                                     <table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(9).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(9).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(9).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(9).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(9).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(9).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(9).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "<table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(10).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(10).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(10).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(10).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(10).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(10).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(10).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "<table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(11).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(11).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(11).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(11).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(11).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(11).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(11).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "<table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(12).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(12).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(12).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(12).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(12).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(12).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(12).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "<table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(13).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(13).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(13).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(13).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(13).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(13).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(13).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "<table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(14).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(14).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(14).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(14).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(14).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(14).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(14).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "</td>\n"
                        + "                            <td class=\"vehicle\">"
                        + "<table>\n"
                        + "                                            <tr>\n"
                        + "                                                <td class=\"driver\">" + vehicleGrid.getVehiclePanelArray().get(15).getDriverName() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(15).getPassenger1() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(15).getPassenger2() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(15).getPassenger3() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><img src=\"" + "file:\\" + vehicleGrid.getVehiclePanelArray().get(15).getIconPath() + "\" alt=\"vehicle\" /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td><hr /></td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(15).getBumperNumber() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td>" + vehicleGrid.getVehiclePanelArray().get(15).getCallSign() + "</td>\n"
                        + "                                            </tr>\n"
                        + "\n"
                        + "                                            <tr>\n"
                        + "                                                <td></td>\n"
                        + "                                            </tr>\n"
                        + "                                        </table>"
                        + "                             </td>\n"
                        + "                        </tr>\n"
                        + "                    </table>\n"
                        + "                </td>\n"
                        + "            </tr>\n"
                        + additionalText
                        + "        </table>\n"
                        + "    </div>\n"
                        + "</body>\n"
                        + "\n"
                        + "</html>");
                
            }

                //Desktop.getDesktop().browse(f.toURI()); open html file in default browser.
            }
        } catch (IOException ex) {
            //ex.printStackTrace();
        }
    }
    
    
    
    public static String getProgramPath() throws UnsupportedEncodingException {
      URL url = convoy.gui.MainMenu.class.getProtectionDomain().getCodeSource().getLocation();
      String jarPath = URLDecoder.decode(url.getFile(), "UTF-8");
      String parentPath = new File(jarPath).getParentFile().getPath();
      return parentPath;
   }
}
