/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package convoy.gui;

import convoy.objects.Personnel;
import convoy.objects.Vehicle;
import javax.swing.JLabel;

/**
 *
 * @author Oakes
 */
public class VehiclePanel extends javax.swing.JPanel {

    public Vehicle vehicle;
    /*
    public void setDriverName() {
        String firstName = vehicle.getDriver().getFirstName();
        String lastName = vehicle.getDriver().getLastName();
        driverNameLabel = new JLabel(firstName + " " + lastName);
    }
    
    public void setPassengerName(JLabel passengerLabel, int passengerNum) {
        Personnel passenger = vehicle.getPassengers().get(passengerNum);
        
        if (passenger != null) {
            String firstName = vehicle.getDriver().getFirstName();
            String lastName = vehicle.getDriver().getLastName();
            passengerLabel = new JLabel(firstName + " " + lastName);
        }
    }
     */
    
    
    /**
     * Creates new form VehiclePanel
     */
    public VehiclePanel() {
        vehicle = new Vehicle();
        vehiclePicturePanel2 = new PicturePanel("/convoy/resources/images/camo.jpg");
        this.setOpaque(false);
        
        //setPassengerName(passenger1NameLabel, 1);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        vehiclePicturePanel2 = new convoy.gui.PicturePanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 178, 128)));
        setName(""); // NOI18N

        jLabel8.setBackground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("jLabel3");
        jLabel8.setMaximumSize(new java.awt.Dimension(50, 11));
        jLabel8.setMinimumSize(new java.awt.Dimension(50, 11));
        jLabel8.setName(""); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 11));

        javax.swing.GroupLayout vehiclePicturePanel2Layout = new javax.swing.GroupLayout(vehiclePicturePanel2);
        vehiclePicturePanel2.setLayout(vehiclePicturePanel2Layout);
        vehiclePicturePanel2Layout.setHorizontalGroup(
            vehiclePicturePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        vehiclePicturePanel2Layout.setVerticalGroup(
            vehiclePicturePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jLabel9.setText("jLabel3");
        jLabel9.setMaximumSize(new java.awt.Dimension(50, 11));
        jLabel9.setMinimumSize(new java.awt.Dimension(50, 11));
        jLabel9.setName(""); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 11));

        jLabel10.setText("jLabel3");
        jLabel10.setMaximumSize(new java.awt.Dimension(50, 11));
        jLabel10.setMinimumSize(new java.awt.Dimension(50, 11));
        jLabel10.setName(""); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 11));

        jLabel11.setText("jLabel3");
        jLabel11.setMaximumSize(new java.awt.Dimension(50, 11));
        jLabel11.setMinimumSize(new java.awt.Dimension(50, 10));
        jLabel11.setName(""); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(50, 11));

        jLabel12.setBackground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("jLabel3");
        jLabel12.setMaximumSize(new java.awt.Dimension(50, 11));
        jLabel12.setMinimumSize(new java.awt.Dimension(50, 11));
        jLabel12.setName(""); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(50, 11));

        jLabel13.setBackground(new java.awt.Color(102, 102, 255));
        jLabel13.setText("jLabel3");
        jLabel13.setMaximumSize(new java.awt.Dimension(50, 11));
        jLabel13.setMinimumSize(new java.awt.Dimension(50, 11));
        jLabel13.setName(""); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(50, 11));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vehiclePicturePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehiclePicturePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel8, jLabel9});

        jLabel8.getAccessibleContext().setAccessibleName("driver");
        jLabel8.getAccessibleContext().setAccessibleDescription("driver");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private convoy.gui.PicturePanel vehiclePicturePanel2;
    // End of variables declaration//GEN-END:variables
}
